server:
  port: ${SERVER_PORT:0}
  error:
    include-stacktrace: never

spring:
  application:
    name: resilientshop-products-api
  #PostgreSQL
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

#Swagger
spring-doc:
  api-docs:
    path: /api-docs

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_NAME:localhost}:8761/eureka
